---
title: "Tidy Data"
output: github_document
date: "2022-09-27"
---

```{r setup, echo=FALSE}
library(tidyverse)
```

## `pivot_longer`

Load the PULSE data

```{r}
pulse_data = 
  haven::read_sas("./data_import_examples/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names()
```

Wide format to long format...
```{r}
pulse_data_tidy = pulse_data %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m, 
    names_to = "visit", #Names of the bdi variable goes under "visit" variable
    names_prefix = "bdi_score_", #Remove prefix 
    values_to = "bdi" #Values of the bdi scores go under "bdi" variable
  )
```
Now let's put all of the data cleaning steps into a single chunk. 
Rewrite, combine, and extend (to add a mutate step).
```{r}
pulse_data = 
  haven::read_sas("./data_import_examples/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m, 
    names_to = "visit", #Names of the bdi variable goes under "visit" variable
    names_prefix = "bdi_score_", #Remove prefix 
    values_to = "bdi" #Values of the bdi scores go under "bdi" variable
  ) %>% 
  relocate(id, visit) %>% # Move ID and visit columns to the front
  mutate(visit = recode(visit, "bl" = "00m")) # Update 'bl' to '00m' in the dataset
```
## `pivot_wider`

Make up some data!

```{r}
analysis_result = 
  tibble(
    group = c("treatment", "treatment", "placebo", "placebo"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 8, 3.5, 4)
  )

analysis_result %>% 
  pivot_wider(
    names_from = "time", 
    values_from = "mean"
  )
```


